platform :ios, '7.0'
pod 'CocoaLumberjack'
pod 'ECSlidingViewController'
pod 'UIColor-HexString'
pod 'RestKit'
pod 'Facebook-iOS-SDK'
pod 'SDWebImage'
pod 'UIImage-Resize'
pod 'ChatHeads'
pod 'UIView+Helpers'
pod 'SSZipArchive'
pod 'MBProgressHUD'
