//
//  TSLocalizedString.h
//  ToSavour
//
//  Created by Jason Wan on 9/12/13.
//  Copyright (c) 2013 NBition. All rights reserved.
//

#ifndef ToSavour_TSLocalizedString_h
#define ToSavour_TSLocalizedString_h

#define LS_SKIP     NSLocalizedString(@"Skip", @"")
#define LS_CANCEL   NSLocalizedString(@"Cancel", @"")
#define LS_CAMERA   NSLocalizedString(@"Camera", @"")
#define LS_PHOTO_LIBRARY    NSLocalizedString(@"Photo Library", @"")
#define LS_CHECK_OUT        NSLocalizedString(@"Check Out", @"")
#define LS_TOTAL            NSLocalizedString(@"Total", @"")
#define LS_TO               NSLocalizedString(@"To", @"")
#define LS_HOME                 NSLocalizedString(@"Home", @"")
#define LS_STORE                NSLocalizedString(@"Store", @"")
#define LS_CART             NSLocalizedString(@"Cart", @"")
#define LS_ME               NSLocalizedString(@"Me", @"")
#define LS_FRIENDS          NSLocalizedString(@"Friends", @"")
#define LS_ACCOUNT          NSLocalizedString(@"Account", @"")
#define LS_DAILY_AWARD_GAME     NSLocalizedString(@"Daily Award Game", @"")
#define LS_AWARDS               NSLocalizedString(@"Awards", @"")
#define LS_CHALLENGE            NSLocalizedString(@"Challenge", @"")
#define LS_ALREADY_PLAYED       NSLocalizedString(@"You have already played this game", @"")
#define LS_ALREADY_WON          NSLocalizedString(@"Yeah! You have already won this game", @"")
#define LS_COFFEE               NSLocalizedString(@"Coffee", @"")
#define LS_ARE_YOU_READY        NSLocalizedString(@"Are You Ready", @"")
#define LS_END                  NSLocalizedString(@"End", @"")
#define LS_END_GAME             NSLocalizedString(@"End Game", @"")
#define LS_END_GAME_DETAILS     NSLocalizedString(@"Are you sure to end this game? You will lose the game", @"")
#define LS_CANCEL               NSLocalizedString(@"Cancel", @"")
#define LS_LOSE_GAME_TITLE      NSLocalizedString(@"Oh! You Lose!", @"")
#define LS_LOSE_GAME_DETAILS    NSLocalizedString(@"Thank you for joining the daily game. Please try again tomorrow", @"")
#define LS_OK                   NSLocalizedString(@"OK", @"")
#define LS_CONGRATULATIONS      NSLocalizedString(@"Congratulations", @"")
#define LS_WIN_GAME_DETAILS     NSLocalizedString(@"You win the daily award game. You received the coffee. Enjoy!", @"")
#define LS_DOWNLOADING          NSLocalizedString(@"Downloading", @"")
#define LS_DOWNLOAD_FAILED      NSLocalizedString(@"Download Failed", @"")
#define LS_DOWNLOAD_FAILED_DETAILS  NSLocalizedString(@"Oops! Download Failed", @"")
#define LS_UNZIP_FAILED         NSLocalizedString(@"The game is not ready", @"")
#define LS_UNZIP_FAILED_DETAILS NSLocalizedString(@"Sorry, the game is not ready, please try again later", @"")
#define LS_LOADING              NSLocalizedString(@"Loading", @"")
#define LS_OOPS                 NSLocalizedString(@"Oops", @"")
#define LS_SERVICE_CALLS_FAILED_GENERAL     NSLocalizedString(@"We have encounter problem when we prepare the game, please try again later.", @"")
#define LS_ADD_TO_CART          NSLocalizedString(@"Add to Cart", @"")
#define LS_QUANTITY             NSLocalizedString(@"Quantity", @"")
#define LS_LAST_ORDER           NSLocalizedString(@"Last Order", @"")
#define LS_ORDER_NOW            NSLocalizedString(@"Order Now", @"")
#define LS_BALANCE              NSLocalizedString(@"Balance", @"")
#define LS_PICK_UP_LOCATION     NSLocalizedString(@"Pick Up Location", @"")
#define LS_FINISH               NSLocalizedString(@"Finish", @"")
#define LS_CONFIRM              NSLocalizedString(@"Confirm", @"")
#define LS_PENDING              NSLocalizedString(@"Pending", @"")
#define LS_IN_PROGRESS          NSLocalizedString(@"In Progress", @"")
#define LS_FINISHED             NSLocalizedString(@"Finished", @"")
#define LS_NUM_NO               NSLocalizedString(@"No.", @"")
#define LS_ORDER_NO             NSLocalizedString(@"Order No.", @"")
#define LS_REF_NO               NSLocalizedString(@"Ref No.", @"")
#define LS_GIFT_FROM            NSLocalizedString(@"Gift from", @"")
#define LS_MY_ORDER             NSLocalizedString(@"My Order", @"")
#define LS_GIFT                 NSLocalizedString(@"Gift", @"")
#define LS_SUBMITTING           NSLocalizedString(@"Submitting", @"")
#define LS_ORDER                NSLocalizedString(@"Order", @"")
#define LS_FREE                 NSLocalizedString(@"Free", @"")
#define LS_REDEEM               NSLocalizedString(@"Redeem", @"")
#define LS_REDEEM_GIFT          NSLocalizedString(@"Redeem Gift", @"")
#define LS_ORDER_DETAILS        NSLocalizedString(@"Order Details", @"")
#define LS_PICK_UP_LOCATION     NSLocalizedString(@"Pick Up Location", @"")
#define LS_ORDER_ITEMS          NSLocalizedString(@"Order Items", @"")
#define LS_INVITE               NSLocalizedString(@"Invite", @"")
#define LS_ERROR                NSLocalizedString(@"Error", @"")
#define LS_LOCATION             NSLocalizedString(@"Location", @"")
#define LS_BUSINESS_HOUR        NSLocalizedString(@"Business Hour", @"")
#define LS_CONTACT_NUMBER       NSLocalizedString(@"Contact Number", @"")
#define LS_ADDRESS              NSLocalizedString(@"Address", @"")
#define LS_STORE_INFO           NSLocalizedString(@"Store Info", @"")
#define LS_DISTANCE_UNAVAILABLE NSLocalizedString(@"Distance Unavailable", @"")
#define LS_RECOMMENDED_TIME     NSLocalizedString(@"Recommended Time", @"")
#define LS_SEARCH_FRIENDS       NSLocalizedString(@"Search Friends", @"")

#endif
